/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package castlepanic;

/**
 *
 * @author Benjamin
 */
public class GameMenu extends javax.swing.JDialog {

    /**
     * Creates new form GameMenu
     */
    public GameMenu(CastleFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuLayeredPane = new javax.swing.JLayeredPane();
        menuBottomLayer = new javax.swing.JPanel();
        titleBackgroundLabel = new javax.swing.JLabel();
        menuTopLayer = new javax.swing.JPanel();
        p3NameField = new javax.swing.JTextField();
        p1NameField = new javax.swing.JTextField();
        p4NameField = new javax.swing.JTextField();
        p5NameField = new javax.swing.JTextField();
        p1Label = new javax.swing.JLabel();
        p2Label = new javax.swing.JLabel();
        p3Label = new javax.swing.JLabel();
        p4Label = new javax.swing.JLabel();
        p5Label = new javax.swing.JLabel();
        p6Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        p6NameField = new javax.swing.JTextField();
        p2NameField = new javax.swing.JTextField();
        textUIButton = new javax.swing.JRadioButton();
        gUIButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Player Names");

        menuLayeredPane.setPreferredSize(new java.awt.Dimension(400, 400));

        menuBottomLayer.setPreferredSize(new java.awt.Dimension(400, 400));

        titleBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titleScreen.png"))); // NOI18N

        javax.swing.GroupLayout menuBottomLayerLayout = new javax.swing.GroupLayout(menuBottomLayer);
        menuBottomLayer.setLayout(menuBottomLayerLayout);
        menuBottomLayerLayout.setHorizontalGroup(
            menuBottomLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBackgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBottomLayerLayout.setVerticalGroup(
            menuBottomLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBottomLayerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titleBackgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuTopLayer.setFocusable(false);
        menuTopLayer.setOpaque(false);
        menuTopLayer.setPreferredSize(new java.awt.Dimension(400, 400));

        p3NameField.setColumns(8);

        p1NameField.setColumns(8);
        p1NameField.setName(""); // NOI18N

        p4NameField.setColumns(8);

        p5NameField.setColumns(8);

        p1Label.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        p1Label.setForeground(new java.awt.Color(153, 153, 153));
        p1Label.setText("Player 1:");
        p1Label.setToolTipText("");

        p2Label.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        p2Label.setForeground(new java.awt.Color(153, 153, 153));
        p2Label.setText("Player 2:");
        p2Label.setToolTipText("");

        p3Label.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        p3Label.setForeground(new java.awt.Color(153, 153, 153));
        p3Label.setText("Player 3:");
        p3Label.setToolTipText("");

        p4Label.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        p4Label.setForeground(new java.awt.Color(153, 153, 153));
        p4Label.setText("Player 4:");
        p4Label.setToolTipText("");

        p5Label.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        p5Label.setForeground(new java.awt.Color(153, 153, 153));
        p5Label.setText("Player 5:");
        p5Label.setToolTipText("");

        p6Label.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        p6Label.setForeground(new java.awt.Color(153, 153, 153));
        p6Label.setText("Player 6:");
        p6Label.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        jButton1.setText("Start!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameMenuStartClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        jButton2.setText("Quit");

        p6NameField.setColumns(8);

        p2NameField.setColumns(8);
        p2NameField.setName(""); // NOI18N
        p2NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2NameFieldActionPerformed(evt);
            }
        });

        textUIButton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(textUIButton);
        textUIButton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        textUIButton.setForeground(new java.awt.Color(204, 204, 204));
        textUIButton.setSelected(true);
        textUIButton.setText("Graphical UI");
        textUIButton.setActionCommand("Graphical");
        textUIButton.setBorder(null);
        textUIButton.setBorderPainted(true);
        textUIButton.setContentAreaFilled(false);
        textUIButton.setPreferredSize(new java.awt.Dimension(100, 21));
        textUIButton.setRolloverEnabled(false);

        gUIButton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(gUIButton);
        gUIButton.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        gUIButton.setForeground(new java.awt.Color(204, 204, 204));
        gUIButton.setText("Text UI");
        gUIButton.setActionCommand("Text");
        gUIButton.setBorder(null);
        gUIButton.setBorderPainted(true);
        gUIButton.setContentAreaFilled(false);
        gUIButton.setPreferredSize(new java.awt.Dimension(100, 21));
        gUIButton.setRolloverEnabled(false);

        javax.swing.GroupLayout menuTopLayerLayout = new javax.swing.GroupLayout(menuTopLayer);
        menuTopLayer.setLayout(menuTopLayerLayout);
        menuTopLayerLayout.setHorizontalGroup(
            menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuTopLayerLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(p6Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p5Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p1Label, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1NameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3NameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4NameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5NameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6NameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2NameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gUIButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textUIButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuTopLayerLayout.setVerticalGroup(
            menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTopLayerLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuTopLayerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(gUIButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUIButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(menuTopLayerLayout.createSequentialGroup()
                        .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1Label))
                        .addGap(3, 3, 3)
                        .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2Label))
                        .addGap(3, 3, 3)
                        .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p3NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3Label))
                        .addGap(3, 3, 3)
                        .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p4NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4Label))
                        .addGap(3, 3, 3)
                        .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p5NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5Label))
                        .addGap(3, 3, 3)
                        .addGroup(menuTopLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p6NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        gUIButton.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout menuLayeredPaneLayout = new javax.swing.GroupLayout(menuLayeredPane);
        menuLayeredPane.setLayout(menuLayeredPaneLayout);
        menuLayeredPaneLayout.setHorizontalGroup(
            menuLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayeredPaneLayout.createSequentialGroup()
                .addComponent(menuBottomLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuTopLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        menuLayeredPaneLayout.setVerticalGroup(
            menuLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayeredPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menuBottomLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(menuLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayeredPaneLayout.createSequentialGroup()
                    .addComponent(menuTopLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        menuLayeredPane.setLayer(menuBottomLayer, 1);
        menuLayeredPane.setLayer(menuTopLayer, 2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameMenuStartClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameMenuStartClicked

        players = new String[6];
        if (p1NameField.getText().equals("") && this.getDecision().equals("Graphical")) {
            System.out.println("GameMenu: Enter at least one player name.");
            return;
        }
        try {
            players[0] = p1NameField.getText();
        } catch (NullPointerException e) {
            System.out.println("GameMenu: Enter at least one player name.");
            return;
        }

        try {
            players[1] = p2NameField.getText();
        } catch (NullPointerException e) {
            players[1] = "";
        }

        try {
            players[2] = p3NameField.getText();
        } catch (NullPointerException e) {
            players[2] = "";
        }

        try {
            players[3] = p4NameField.getText();
        } catch (NullPointerException e) {
            players[3] = "";
        }

        try {
            players[4] = p5NameField.getText();
        } catch (NullPointerException e) {
            players[4] = "";
        }

        try {
            players[5] = p6NameField.getText();
        } catch (NullPointerException e) {
            players[5] = "";
        }
        this.setModal(false);
        this.dispose();
        for (String name : players) {
            System.out.println("GameMenu: Player - " + name);
           
        }
        



    }//GEN-LAST:event_gameMenuStartClicked

    private void p2NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2NameFieldActionPerformed
    public String[] getPlayerNames() {
        return players;
    }
    public String getDecision() {
        String selected = this.buttonGroup1.getSelection().getActionCommand();
        return selected;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton gUIButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel menuBottomLayer;
    private javax.swing.JLayeredPane menuLayeredPane;
    private javax.swing.JPanel menuTopLayer;
    private javax.swing.JLabel p1Label;
    private javax.swing.JTextField p1NameField;
    private javax.swing.JLabel p2Label;
    private javax.swing.JTextField p2NameField;
    private javax.swing.JLabel p3Label;
    private javax.swing.JTextField p3NameField;
    private javax.swing.JLabel p4Label;
    private javax.swing.JTextField p4NameField;
    private javax.swing.JLabel p5Label;
    private javax.swing.JTextField p5NameField;
    private javax.swing.JLabel p6Label;
    private javax.swing.JTextField p6NameField;
    private javax.swing.JRadioButton textUIButton;
    private javax.swing.JLabel titleBackgroundLabel;
    // End of variables declaration//GEN-END:variables
    private String[] players;
}