/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package castlepanic;

/**
 *
 * @author Benjamin
 */
public class ItsCurtains extends javax.swing.JDialog {

    /**
     * Creates new form GameMenu
     */
    public ItsCurtains(CastleFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuLayeredPane = new javax.swing.JLayeredPane();
        menuBottomLayer = new javax.swing.JPanel();
        titleBackgroundLabel = new javax.swing.JLabel();
        menuBottomLayer1 = new javax.swing.JPanel();
        titleBackgroundLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Player Names");

        menuLayeredPane.setPreferredSize(new java.awt.Dimension(400, 400));

        menuBottomLayer.setPreferredSize(new java.awt.Dimension(400, 400));

        titleBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titleScreen.png"))); // NOI18N

        javax.swing.GroupLayout menuBottomLayerLayout = new javax.swing.GroupLayout(menuBottomLayer);
        menuBottomLayer.setLayout(menuBottomLayerLayout);
        menuBottomLayerLayout.setHorizontalGroup(
            menuBottomLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBackgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBottomLayerLayout.setVerticalGroup(
            menuBottomLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBottomLayerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titleBackgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBottomLayer1.setPreferredSize(new java.awt.Dimension(400, 400));

        titleBackgroundLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titleScreen.png"))); // NOI18N

        javax.swing.GroupLayout menuBottomLayer1Layout = new javax.swing.GroupLayout(menuBottomLayer1);
        menuBottomLayer1.setLayout(menuBottomLayer1Layout);
        menuBottomLayer1Layout.setHorizontalGroup(
            menuBottomLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBackgroundLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBottomLayer1Layout.setVerticalGroup(
            menuBottomLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBottomLayer1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titleBackgroundLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuLayeredPaneLayout = new javax.swing.GroupLayout(menuLayeredPane);
        menuLayeredPane.setLayout(menuLayeredPaneLayout);
        menuLayeredPaneLayout.setHorizontalGroup(
            menuLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayeredPaneLayout.createSequentialGroup()
                .addGroup(menuLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuBottomLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBottomLayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        menuLayeredPaneLayout.setVerticalGroup(
            menuLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayeredPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menuBottomLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuBottomLayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuLayeredPane.setLayer(menuBottomLayer, 1);
        menuLayeredPane.setLayer(menuBottomLayer1, 2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String[] getPlayerNames() {
        return players;
    }
    public String getDecision() {
        String selected = this.buttonGroup1.getSelection().getActionCommand();
        return selected;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel menuBottomLayer;
    private javax.swing.JPanel menuBottomLayer1;
    private javax.swing.JLayeredPane menuLayeredPane;
    private javax.swing.JLabel titleBackgroundLabel;
    private javax.swing.JLabel titleBackgroundLabel1;
    // End of variables declaration//GEN-END:variables
    private String[] players;
}